// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111152836_DataAnnotationsUpdate")]
    partial class DataAnnotationsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.BatchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerBatchId");

                    b.HasIndex("UserId");

                    b.ToTable("BatchLogs");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BeerBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerSortId")
                        .HasColumnType("int");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BeerSortId");

                    b.ToTable("BeerBatches");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BeerSort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BeerSorts");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BeerBatchId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("BeerBatchId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TasteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerBatchId");

                    b.HasIndex("UserId");

                    b.ToTable("TasteLogs");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BatchLog", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.BeerBatch", "BeerBatch")
                        .WithMany("Logs")
                        .HasForeignKey("BeerBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.User", "User")
                        .WithMany("BatchLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerBatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BeerBatch", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.BeerSort", "BeerSort")
                        .WithMany("Batches")
                        .HasForeignKey("BeerSortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerSort");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Ingredient", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.BeerBatch", "BeerBatch")
                        .WithMany("Ingredients")
                        .HasForeignKey("BeerBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerBatch");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Photo", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.BeerBatch", "BeerBatch")
                        .WithMany("Photos")
                        .HasForeignKey("BeerBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerBatch");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TasteLog", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.BeerBatch", "BeerBatch")
                        .WithMany("TasteLogs")
                        .HasForeignKey("BeerBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.User", "User")
                        .WithMany("TasteLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerBatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BeerBatch", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Logs");

                    b.Navigation("Photos");

                    b.Navigation("TasteLogs");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.BeerSort", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.User", b =>
                {
                    b.Navigation("BatchLogs");

                    b.Navigation("TasteLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
